// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "CatHome.h"
CatHome::CatHome() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::catapult);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	SetTimeout(.1);
}
// Called just before this Command runs the first time
void CatHome::Initialize() {
	Robot::catapult->CatLimitOut(-.35, .35);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZE
	Robot::catapult->Enable();
	Robot::catapult->SetSetpoint(50);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZE
}
// Called repeatedly when this Command is scheduled to run
void CatHome::Execute() {
}
// Make this return true when this Command no longer needs to run execute()
bool CatHome::IsFinished() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ISFINISHED
	return (Robot::catapult->OnTarget() || IsTimedOut());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ISFINISHED
}
// Called once after isFinished returns true
void CatHome::End() {
	Robot::catapult->CatLimitOut(-1.0, .35);
	Robot::catapult->Disable();
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void CatHome::Interrupted() {
	End();
}
