// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Tilt.h"
#include "../Robotmap.h"
Tilt::Tilt() : Subsystem("Tilt") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	tilt = RobotMap::tiltTilt;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void Tilt::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
void Tilt::Up(){
	tilt->Set(DoubleSolenoid::kReverse);
}
void Tilt::Down(){
	tilt->Set(DoubleSolenoid::kForward);
}
void Tilt::Off(){
	tilt->Set(DoubleSolenoid::kOff);
}
void Tilt::ToggleTilt(){
	switch (tilt->Get()){
	case DoubleSolenoid::kForward:
			Up();
			break;
	case DoubleSolenoid::kReverse:
			Down();
			break;
	case DoubleSolenoid::kOff:
			Down();
			break;
	default:
			Off();
			break;
	}
}
